language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-9
    - libboost-graph-dev
    - libboost-dev
    - libexpat1-dev
    - libbz2-dev
    - zlib1g
    - zlib1g-dev
env:
  - CXX=g++-9
install:
  - git submodule sync
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
script:
  - make tests -j8
  - ./coreset_testdbg
  - ./btestdbg
  - ./kmpptestdbg
  - ./jvtestdbg
  - ./tbmdbg
  - ./tbasdbg
  - ./diskmattestdbg
  - ./dmlsearchdbg
  - ./jsdhashdbg
  - ./fgcinctestdbg
  - ./geomedtestdbg
  - ./sparsepriortestdbg
  - ./istestdbg
  - ./msvdbg
  - ./knntestdbg
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
